<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="1" hostname="13d58b3f5b8d" name="pytest" skipped="0" tests="3" time="0.174" timestamp="2022-08-11T17:43:27.971060"><testcase classname="tests.functional.test_dashboard" name="test_dashboard" time="0.011" /><testcase classname="tests.functional.test_fail" name="test_fail" time="0.003"><failure message="assert 404 == 200&#10; +  where 404 = &lt;WrapperTestResponse streamed [404 NOT FOUND]&gt;.status_code">def test_fail():
      flask_app = create_app('flask_test.cfg')

      with flask_app.test_client() as test_client:
        response = test_client.get('/fail')
&gt;       assert response.status_code == 200
E       assert 404 == 200
E        +  where 404 = &lt;WrapperTestResponse streamed [404 NOT FOUND]&gt;.status_code

tests/functional/test_fail.py:8: AssertionError</failure></testcase><testcase classname="tests.functional.test_unknown" name="test_unknown" time="0.005" /></testsuite></testsuites>